import { Emoji } from "../types";

export const EMOJI_DATA = {
  smile: "😄",
  heartEyes: "😍",
  angry: "😠",
  sob: "😭",
  heart: "❤️",
  purpleHeart: "💜",
  noEntrySign: "🚫",
  warning: "⚠️",
  memo: "📝",
  alarm: "⏰",
  phone: "📱",
  game: "🎮",
  computer: "💻",
  pray: "🙏",
  tada: "🎉",
  gift: "🎁",
  popcorn: "🍿",
  musicalNote: "🎵",
  dollar: "💵",
  creditCard: "💳",
  calendar: "📆",
  chart: "📊",
  bulb: "💡",
  shoppingTrolley: "🛒",
  bath: "🛁",
  fries: "🍟",
  cake: "🍰",
  apple: "🍎",
  carrot: "🥕",
  airplane: "✈️",
  bus: "🚍",
  metro: "🚇",
  house: "🏠",
  tent: "🏕️",
  star: "⭐",
  sunny: "☀️",
  rainbow: "🌈",
  rain: "☂️",
  snowman: "☃️",
  blossom: "🌸",
};

export const EMOJI_ARRAY: Emoji[] = Object.keys(EMOJI_DATA).sort() as Emoji[];
