export const SESSION_KEY = {
  originTemplate: "originTemplate",
  blockQuickMenuTarget: "blockQuickMenuTarget",
  blockToBeEdited: "blockToBeEdited",
  mainCommentId: "mainCommentId",
  newBlock: "newBlock",
  modalStyle: "modalStyle",
  editComment: "editComment",
  toolMoreItem: "toolMoreItem",
  mobileMenuTargetBlock: "mobileMenuTargetBlock",
  mobileSideMenuBlock: "mobileSideMenuBlock",
  targetPageId: "targetPageId",
  originMoveTargetPage: "originMoveTargetPage",
  recentPages: "recentPages",
  loaderTargetBlock: "loaderTargetBlock",
};
